Feature/task3
modrzej/java101 pull request #4
Opened 2017-01-24 20:45 UTC by amodrzeja

2017-01-24 21:13 UTC, modrzej requested changes

2017-01-24 21:13 UTC, modrzej commented on java101/src/com/java101/HeroService.java
> +	public List<Hero> showHeroesListFromJsonFile() throws ParseException, IOException {
To dalej pokazuje bohaterów? :P

2017-01-24 21:13 UTC, modrzej commented on java101/src/com/java101/HeroService.java
> -				System.out.println(heroesList.get(i));
Czemu usunęłaś wnętrze pętli, a same pętle zostawiłaś? :D

2017-01-24 21:13 UTC, modrzej commented on java101/src/com/java101/HeroService.java
> +		logger.debug(heroesList);
Wyżej logujesz na INFO a tutaj na debug? :) Czemu? :)

2017-01-24 21:13 UTC, modrzej commented on java101/src/com/java101/Application.java
> +@Controller
@Controller jest tu potrzebny? Spróbuj bez niego :)

2017-01-25 20:54 UTC, amodrzeja commented on java101/src/com/java101/HeroService.java
> +	public List<Hero> showHeroesListFromJsonFile() throws ParseException, IOException {
No w sumie, ta metoda jest na tą chwilę niepotrzebna. Usunęłam ją.

2017-01-25 20:54 UTC, amodrzeja commented on java101/src/com/java101/HeroService.java
> -				System.out.println(heroesList.get(i));
Cała metoda już jest usunięta.

2017-01-25 20:56 UTC, amodrzeja commented on java101/src/com/java101/Application.java
> +@Controller
Racja, już jest niepotrzebny. Został przypadkowo jak ćwiczyłam połączenie z przeglądarką.

2017-01-26 15:25 UTC, modrzej approved these changes

2017-01-26 20:23 UTC, merged