Feature/task4
modrzej/java101 pull request #6
Opened 2017-02-12 09:41 UTC by amodrzeja

2017-02-12 17:02 UTC, modrzej requested changes

2017-02-12 17:02 UTC, modrzej commented on java101/pom.xml
> +		<java.version>1.7</java.version>
Korzystasz z javy 8, po co Ci ten property na jave 7? : P nawet nigdzie go nie używasz :P

2017-02-12 17:02 UTC, modrzej commented on java101/src/main/java/com/java101/Application.java
> +
niepotrzebna pusta linia :P

2017-02-12 17:02 UTC, modrzej commented on java101/src/main/java/com/java101/HeroService.java
> +	}*/
A po co ten zakomentowany kod? : >

2017-02-12 17:02 UTC, modrzej commented on java101/src/main/webapp/heroes.ftl
> +    	#tabela {
#tabela jest po polsku ; p

2017-02-12 17:02 UTC, modrzej commented on java101/src/main/webapp/heroes.ftl
> +	<tr>
do nagłówków jest <thead> tak jak niżej użyłaś <tbody>

2017-02-12 17:02 UTC, modrzej commented on java101/src/main/webapp/heroes.ftl
> +</table>
Sformatuj tu cały kod

2017-02-12 17:02 UTC, modrzej commented on java101/src/main/webapp/index.html
> +    <h2>Spring Boot Hello World Example with FreeMarker</h2>
A hello world po co? :) Możesz tu dać linka do heroes.

2017-02-13 19:55 UTC, amodrzeja commented on java101/src/main/java/com/java101/Application.java
> +
Usunięta.

2017-02-13 19:56 UTC, amodrzeja commented on java101/pom.xml
> +		<java.version>1.7</java.version>
Racja. Już jej nie ma.

2017-02-13 19:57 UTC, amodrzeja commented on java101/src/main/java/com/java101/HeroService.java
> +	}*/
Nie wiedziałam, czy będzie jezscze potrzebny to zakomentowałam.

2017-02-13 19:57 UTC, amodrzeja commented on java101/src/main/webapp/heroes.ftl
> +    	#tabela {
Ok. Zmieniam na angielski.

2017-02-13 20:30 UTC, amodrzeja commented on java101/src/main/webapp/heroes.ftl
> +</table>
Nie mogę w necie znaleźć skrótu klawiszowego do formatowania. ctrl+shift+f nie działa w pliku ftl. jest jakiś inny ?

2017-02-15 17:07 UTC, modrzej commented on java101/src/main/webapp/heroes.ftl
> +</table>
http://stackoverflow.com/questions/4044414/format-freemarker-files-in-eclipse

2017-02-15 17:08 UTC, modrzej approved these changes

2017-02-22 17:32 UTC, amodrzeja commented on java101/src/main/webapp/heroes.ftl
> +</table>
ok

2017-02-22 17:33 UTC, merged